# Bridge to Data — Your First Step into pandas

This notebook was completed as part of Week 4 of my internship at Sohail Smart Solutions.

The goal of this task is to move from object-oriented programming into basic data handling using pandas.

## Part 1 — Learn

### Why AI Work Needs a Data Tool

AI work needs data. At first, we can store data using lists, dictionaries, or objects. But when the data becomes bigger, it becomes difficult to manage everything manually.

For example, if we have only 3 students, using objects is fine. But if we have hundreds or thousands of records, it becomes harder to calculate averages, filter data, or count values using only normal Python loops.

This is why pandas is useful. Pandas helps us work with data in table format. It makes it easier to load, inspect, filter, and analyze data.

### DataFrame and Series

A DataFrame is like a table in pandas. It has rows and columns, similar to an Excel sheet.

A Series is one column from a DataFrame. For example, if the full table is a DataFrame, then the `grade` column alone is a Series.

### Loading Data from CSV

A CSV file stores data in table format. In pandas, we can load a CSV file using:

`pd.read_csv("students.csv")`

This reads the CSV file and converts it into a DataFrame.

### Inspecting Data

Pandas has useful commands to understand the data:

- `.head()` shows the first few rows.
- `.info()` shows column names and data types.
- `.describe()` gives basic statistics.
- `.shape` shows the number of rows and columns.

### Selecting Columns and Filtering Rows

We can select one column like this:

`df["grade"]`

We can filter rows like this:

`df[df["grade"] > 80]`

This shows only the students who scored above 80.

### Basic Statistics

Pandas can calculate basic statistics easily.

For example:

`df["grade"].mean()`

This gives the average grade.

Also:

`df["course"].value_counts()`

This counts how many times each course appears.

In [7]:
import pandas as pd

data = {
    "student_id": ["S001", "S002", "S003"],
    "name": ["Haameed", "Ahmed", "Sara"],
    "course": ["Python OOP Level 2", "Python OOP Level 2", "Python OOP Level 2"],
    "grade": [85, 78, 92]
}

df = pd.DataFrame(data)

df.to_csv("students.csv", index=False)

print("students.csv created successfully.")

students.csv created successfully.

## Part 2 — Apply

### Loading the CSV File

Now I will load the student data from the CSV file using pandas.

In [5]:
df = pd.read_csv("students.csv")
df

  student_id     name              course  grade
0       S001  Haameed  Python OOP Level 2     85
1       S002    Ahmed  Python OOP Level 2     78
2       S003     Sara  Python OOP Level 2     92

### Inspecting the Data

I used pandas commands to check and understand the dataset.

In [8]:
df.head()

  student_id     name              course  grade
0       S001  Haameed  Python OOP Level 2     85
1       S002    Ahmed  Python OOP Level 2     78
2       S003     Sara  Python OOP Level 2     92

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  3 non-null      object
 1   name        3 non-null      object
 2   course      3 non-null      object
 3   grade       3 non-null      int64
dtypes: int64(1), object(3)
memory usage: 228.0+ bytes

In [10]:
df.describe()

       grade
count    3.0
mean    85.0
std      7.0
min     78.0
25%     81.5
50%     85.0
75%     88.5
max     92.0

In [11]:
df.shape

(3, 4)

### Selecting Columns and Filtering Rows

Here I selected the grade column and filtered students who scored above 80.

In [12]:
df["grade"]

0    85
1    78
2    92
Name: grade, dtype: int64

In [13]:
df[df["grade"] > 80]

  student_id     name              course  grade
0       S001  Haameed  Python OOP Level 2     85
2       S003     Sara  Python OOP Level 2     92

### Question 1: What is the average grade of the students?

In [14]:
average_grade = df["grade"].mean()
average_grade

np.float64(85.0)

Answer: The average grade of the students is 85.0.

### Question 2: How many students scored above 80?

In [15]:
students_above_80 = df[df["grade"] > 80]
len(students_above_80)

2

Answer: 2 students scored above 80.

### Question 3: What is the most common course?

In [16]:
df["course"].value_counts()

course
Python OOP Level 2    3
Name: count, dtype: int64

Answer: The most common course is Python OOP Level 2.

## Short Note — OOP Classes vs pandas

In my OOP project, I used classes like `Student` and `Course` to organize the data. This was useful for building a small program because each object had its own details and methods.

With pandas, the data is handled more like a table. This makes it easier to inspect, filter, and calculate from the data.

For example, in OOP I may need to write loops to calculate the average grade. In pandas, I can do it in one line using:

`df["grade"].mean()`

So, OOP is useful for designing programs and objects. Pandas is useful for working with datasets and doing analysis.