# Week 5 — Data Cleaning with pandas

In this notebook, I am practicing data cleaning using pandas.  
For this task, I used a deliberately messy student dataset based on my Week 4 student analytics data.

The dataset includes common real-world data problems such as missing values, duplicate rows, inconsistent text formatting, and wrong data types.

In [1]:
# Creating a deliberately messy CSV file for the task

messy_data = """student_id,name,university,course,grade
S001, haameed , AURAK ,python oop,85
S002,AHMED,aurak,Python OOP,78
S003,Sara,Aurak ,DATA HANDLING,92
S003,Sara,Aurak ,DATA HANDLING,92
S004,,AURAK,data handling,88
S005,Omar, aurak ,AI Basics,seventy four
S006,Mariam,, ai basics ,90
S007,Yousef,AURAK,Python OOP,
S008, lina,aurak ,python oop,82
"""

with open("messy_students.csv", "w") as file:
    file.write(messy_data)

print("messy_students.csv file created successfully.")

messy_students.csv file created successfully.

In [2]:
import pandas as pd

df = pd.read_csv("messy_students.csv")

print("Original Messy Dataset:")
df

Original Messy Dataset:

  student_id       name university         course         grade
0       S001   haameed      AURAK      python oop            85
1       S002      AHMED      aurak     Python OOP            78
2       S003       Sara     Aurak   DATA HANDLING            92
3       S003       Sara     Aurak   DATA HANDLING            92
4       S004        NaN      AURAK  data handling            88
5       S005       Omar     aurak       AI Basics  seventy four
6       S006     Mariam        NaN     ai basics             90
7       S007     Yousef      AURAK     Python OOP           NaN
8       S008       lina     aurak      python oop            82

## Original Messy Dataset

The dataset has been intentionally made messy for practice.  
Some of the problems include:

- Extra spaces in names and university values
- Different capitalization in text columns
- One duplicate student row
- One missing student name
- One missing university value
- One missing grade
- One grade written as text instead of a number

In [3]:
print("Dataset Information:")
df.info()

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  9 non-null      object
 1   name        8 non-null      object
 2   university  8 non-null      object
 3   course      9 non-null      object
 4   grade       8 non-null      object
dtypes: object(5)
memory usage: 492.0+ bytes

In [4]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

Missing Values in Each Column:
student_id    0
name          1
university    1
course        0
grade         1
dtype: int64

In [5]:
print("Number of Duplicate Rows:")
print(df.duplicated().sum())

Number of Duplicate Rows:
1

In [6]:
print("Data Types:")
print(df.dtypes)

Data Types:
student_id    object
name          object
university    object
course        object
grade         object
dtype: object

In [7]:
# Creating a copy of the original dataset before cleaning
df_cleaned = df.copy()

In [8]:
# Fixing the wrong text value in the grade column
df_cleaned["grade"] = df_cleaned["grade"].replace("seventy four", "74")

# Converting grade column into numeric data type
df_cleaned["grade"] = pd.to_numeric(df_cleaned["grade"], errors="coerce")

print("Grade column after converting to numeric:")
print(df_cleaned["grade"])

Grade column after converting to numeric:
0    85.0
1    78.0
2    92.0
3    92.0
4    88.0
5    74.0
6    90.0
7     NaN
8    82.0
Name: grade, dtype: float64

In [9]:
# Handling missing values

# Remove rows where student name is missing because name is important
df_cleaned = df_cleaned.dropna(subset=["name"])

# Fill missing university values with "Unknown"
df_cleaned["university"] = df_cleaned["university"].fillna("Unknown")

# Fill missing grade values with the average grade
average_grade = df_cleaned["grade"].mean()
df_cleaned["grade"] = df_cleaned["grade"].fillna(average_grade)

print("Missing values after handling:")
print(df_cleaned.isnull().sum())

Missing values after handling:
student_id    0
name          0
university    0
course        0
grade         0
dtype: int64

In [10]:
# Removing duplicate rows
df_cleaned = df_cleaned.drop_duplicates()

print("Number of duplicate rows after cleaning:")
print(df_cleaned.duplicated().sum())

Number of duplicate rows after cleaning:
0

In [11]:
# Standardizing name column
df_cleaned["name"] = df_cleaned["name"].str.strip().str.title()

# Standardizing university column
df_cleaned["university"] = df_cleaned["university"].str.strip().str.lower()
df_cleaned["university"] = df_cleaned["university"].replace({
    "aurak": "AURAK",
    "unknown": "Unknown"
})

# Standardizing course column
df_cleaned["course"] = df_cleaned["course"].str.strip().str.lower()
df_cleaned["course"] = df_cleaned["course"].replace({
    "python oop": "Python OOP",
    "data handling": "Data Handling",
    "ai basics": "AI Basics"
})

print("Text columns after standardization:")
df_cleaned

Text columns after standardization:

  student_id     name university         course      grade
0       S001  Haameed      AURAK     Python OOP  85.000000
1       S002    Ahmed      AURAK     Python OOP  78.000000
2       S003     Sara      AURAK  Data Handling  92.000000
5       S005     Omar      AURAK      AI Basics  74.000000
6       S006   Mariam    Unknown      AI Basics  90.000000
7       S007   Yousef      AURAK     Python OOP  84.714286
8       S008     Lina      AURAK     Python OOP  82.000000

In [12]:
print("Cleaned Dataset Information:")
df_cleaned.info()

Cleaned Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 8
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  7 non-null      object
 1   name        7 non-null      object
 2   university  7 non-null      object
 3   course      7 non-null      object
 4   grade       7 non-null      float64
dtypes: float64(1), object(4)
memory usage: 336.0+ bytes

In [13]:
print("Missing Values After Cleaning:")
print(df_cleaned.isnull().sum())

Missing Values After Cleaning:
student_id    0
name          0
university    0
course        0
grade         0
dtype: int64

In [14]:
print("Duplicate Rows After Cleaning:")
print(df_cleaned.duplicated().sum())

Duplicate Rows After Cleaning:
0

In [15]:
print("Data Types After Cleaning:")
print(df_cleaned.dtypes)

Data Types After Cleaning:
student_id     object
name           object
university     object
course         object
grade         float64
dtype: object

In [16]:
print("Before Cleaning:")
display(df)

print("After Cleaning:")
display(df_cleaned)

Before Cleaning:

  student_id       name university         course         grade
0       S001   haameed      AURAK      python oop            85
1       S002      AHMED      aurak     Python OOP            78
2       S003       Sara     Aurak   DATA HANDLING            92
3       S003       Sara     Aurak   DATA HANDLING            92
4       S004        NaN      AURAK  data handling            88
5       S005       Omar     aurak       AI Basics  seventy four
6       S006     Mariam        NaN     ai basics             90
7       S007     Yousef      AURAK     Python OOP           NaN
8       S008       lina     aurak      python oop            82

After Cleaning:

  student_id     name university         course      grade
0       S001  Haameed      AURAK     Python OOP  85.000000
1       S002    Ahmed      AURAK     Python OOP  78.000000
2       S003     Sara      AURAK  Data Handling  92.000000
5       S005     Omar      AURAK      AI Basics  74.000000
6       S006   Mariam    Unknown      AI Basics  90.000000
7       S007   Yousef      AURAK     Python OOP  84.714286
8       S008     Lina      AURAK     Python OOP  82.000000

In [17]:
df_cleaned.to_csv("cleaned_students.csv", index=False)

print("cleaned_students.csv file saved successfully.")

cleaned_students.csv file saved successfully.

## Summary: The 3 Cleaning Steps That Mattered Most and Why

The first important cleaning step was handling missing values. One student name was missing, so I removed that row because the student could not be identified properly. For the missing university value, I filled it with `"Unknown"` because it was not the main column used for grade analysis. For the missing grade value, I filled it with the average grade so that the student record could still be used.

The second important step was removing duplicate rows. One student record was repeated, and keeping it would have affected the student count and average grade. Removing duplicates made the dataset more accurate.

The third important step was standardizing text and fixing the grade data type. Some names, university values, and course names had extra spaces or different capitalization. I cleaned them using string methods like `.str.strip()` and `.str.lower()`. I also converted the grade column into numeric form because grades must be numbers for calculations such as averages.

Overall, this task helped me understand that data cleaning is an important step before doing analysis or machine learning. Even a small dataset can have problems, and if those problems are not fixed, the final results can become wrong.